version: '3'

services:
  sample:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "start"]
    image: sample-reactjs:latest
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3010:3000